### ISSUE TITLE
Game Refuse To Connect Wynncraft Server with Wyntil Mod 

### ISSUE THREAD

**Issue by ssaagamemer** [huanghongxun/HMCL-PE#122]
**Describe the bug**
Connect A Wynncraft With Wyntil mod And Game Refuse To Connect And Send Disconnect

**To Reproduce**
1. Login To Microsoft Account
2. launch 1.12.2 forge with Wyntil Mod
3. Click Wynncraft Server Icon (Multiplayer → Wynncraft Server)
4. And Game Refuse To Connect

**Paste logs here**

<details>
<summary> Fatal Error</summary>

```
[08:43:10] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:48) [h.class:?]
	at bib.az(SourceFile:991) [bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NullPointerException
	at bhk.d(SourceFile:228) ~[bhk.class:?]
	at brz.a(SourceFile:1694) ~[brz.class:?]
	at kl.a(SourceFile:117) ~[kl.class:?]
	at kl.a(SourceFile:13) ~[kl.class:?]
	at hv$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:47) ~[h.class:?]
	... 9 more
[08:43:22] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:48) [h.class:?]
	at bib.az(SourceFile:991) [bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NullPointerException
	at bhk.d(SourceFile:228) ~[bhk.class:?]
	at brz.a(SourceFile:1694) ~[brz.class:?]
	at kl.a(SourceFile:117) ~[kl.class:?]
	at kl.a(SourceFile:13) ~[kl.class:?]
	at hv$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:47) ~[h.class:?]
	... 9 more
[08:46:06] [main/FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
	at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:48) [h.class:?]
	at bib.az(SourceFile:991) [bib.class:?]
	at bib.a(SourceFile:419) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0-internal]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0-internal]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0-internal]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159) [launchwrapper-of-2.2.jar:2.2]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30) [launchwrapper-of-2.2.jar:2.2]
Caused by: java.lang.NullPointerException
	at bhk.d(SourceFile:228) ~[bhk.class:?]
	at brz.a(SourceFile:1694) ~[brz.class:?]
	at kl.a(SourceFile:117) ~[kl.class:?]
	at kl.a(SourceFile:13) ~[kl.class:?]
	at hv$1.run(PacketThreadUtil.java:22) ~[hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0-internal]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0-internal]
	at h.a(Util.java:47) ~[h.class:?]
	... 9 more


```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**
Connect With Modern Class Selection

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Redmi Note 10 
 - OS: Android 11 (MIUI 13.0.10)
 - Version lastest-dev

**Additional context**

**Comment by ssaagamemer** [comment]
Closed By Fixing Screen DPI
