### ISSUE TITLE
Decocraft mod crash

### ISSUE THREAD

**Issue by LimeWise** [huanghongxun/HMCL-PE#192]
Anytime I download decocraft modand try to play it would crash

 
Stack trace:  
java.lang.IllegalArgumentException: MALFORMED[1]
	at java.util.zip.ZipCoder.toString(ZipCoder.java:65)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:626)
	at java.util.zip.ZipFile.access$900(ZipFile.java:64)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:584)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:559)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:540)
	at com.tungsten.hmclpe.utils.io.ZipTools.unzipFile(ZipTools.java:215)
	at com.tungsten.hmclpe.utils.io.ZipTools.unzipFile(ZipTools.java:185)
	at com.tungsten.hmclpe.launcher.game.World.loadFromZip(World.java:88)
	at com.tungsten.hmclpe.launcher.game.World.<init>(World.java:46)
	at com.tungsten.hmclpe.launcher.game.World.lambda$getWorlds$2(World.java:205)
	at com.tungsten.hmclpe.launcher.game.World$$ExternalSyntheticLambda0.apply(Unknown Source:2)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:280)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:517)
	at com.tungsten.hmclpe.launcher.uis.game.manager.right.WorldManagerUI.lambda$refreshList$5$com-tungsten-hmclpe-launcher-uis-game-manager-right-WorldManagerUI(WorldManagerUI.java:177)
	at com.tungsten.hmclpe.launcher.uis.game.manager.right.WorldManagerUI$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)

**Comment by root-S7** [comment]
zip文件里含有中文名称的文件,windows 环境下，默认字符集为GBK，ZipFile 默认使用 UTF-8 字符集，当文件名存在中文时，处理时就会报错。
稍后推进修复
