### ISSUE TITLE
1.20游戏启动失败

### ISSUE THREAD

**Issue by JSenyu** [huanghongxun/HMCL-PE#199]
手机型号：荣耀magic4
系统版本：magicOS 7.0.0.153 (C00E153R10P7patch05)
安卓版本：13

不是很懂，还以为是权限问题，但是之前1.16.5都是可以正常启动的，就放弃尝试了

希望作者大大可以帮帮我，不然摸鱼的时候都没法跟小伙伴联机了，给你三连了

日志是在游戏目录 HMCLPE/.minecraft/logs 文件夹找到的 latest.log，看了一下时间是刚刚的应该是这个了

[03:21:04] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.a(SourceFile:75) ~[1.20-.jar:?]
	at ab.c(SourceFile:52) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20-.jar:?]
	at o.<init>(SourceFile:34) ~[1.20-.jar:?]
	at o.h(SourceFile:274) ~[1.20-.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:164) ~[1.20-.jar:?]
[03:21:04] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.a(SourceFile:77) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.a(SourceFile:77) ~[1.20-.jar:?]
	at ab.c(SourceFile:52) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20-.jar:?]
	at o.<init>(SourceFile:34) ~[1.20-.jar:?]
	at o.h(SourceFile:274) ~[1.20-.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:164) ~[1.20-.jar:?]
[03:21:08] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 202 milliseconds
[03:21:10] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[03:21:10] [Render thread/INFO]: [STDERR]: [LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[03:21:10] [Render thread/INFO]: [STDERR]: [LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.
[03:21:10] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[03:21:11] [Render thread/ERROR]: Failed to verify authentication
com.mojang.authlib.exceptions.InvalidCredentialsException: Status: 401
	at com.mojang.authlib.exceptions.MinecraftClientHttpException.toAuthenticationException(MinecraftClientHttpException.java:56) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:156) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.<init>(YggdrasilUserApiService.java:55) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.createUserApiService(YggdrasilAuthenticationService.java:124) ~[authlib-4.0.43.jar:?]
	at enn.a(SourceFile:733) ~[1.20-.jar:?]
	at enn.<init>(SourceFile:442) ~[1.20-.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:211) ~[1.20-.jar:?]
Caused by: com.mojang.authlib.exceptions.MinecraftClientHttpException: Status: 401
	at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:85) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:48) ~[authlib-4.0.43.jar:?]
	at com.mojang.authlib.yggdrasil.YggdrasilUserApiService.fetchProperties(YggdrasilUserApiService.java:129) ~[authlib-4.0.43.jar:?]
	... 5 more
[03:21:11] [Render thread/INFO]: Setting user: yuyu
[03:21:11] [Render thread/INFO]: Backend library: LWJGL version 3.2.3 SNAPSHOT
[03:21:11] [Render thread/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.c(SourceFile:75) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.a(SourceFile:75) ~[1.20-.jar:?]
	at ab.c(SourceFile:52) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20-.jar:?]
	at o.<init>(SourceFile:34) ~[1.20-.jar:?]
	at o.a(SourceFile:266) ~[1.20-.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:217) ~[1.20-.jar:?]
[03:21:11] [Render thread/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.hardware.platform.linux.LinuxGlobalMemory
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at ab.a(SourceFile:77) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.a(SourceFile:77) ~[1.20-.jar:?]
	at ab.c(SourceFile:52) ~[1.20-.jar:?]
	at ab.a(SourceFile:82) ~[1.20-.jar:?]
	at ab.<init>(SourceFile:52) ~[1.20-.jar:?]
	at o.<init>(SourceFile:34) ~[1.20-.jar:?]
	at o.a(SourceFile:266) ~[1.20-.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:217) ~[1.20-.jar:?]

**Comment by root-S7** [comment]
https://github.com/huanghongxun/HMCL-PE/issues/198#issuecomment-1630479318
