### ISSUE TITLE
Any version above 1.19.2 crashes [PLEASE RESPOND IN ENGLISH] 

### ISSUE THREAD

**Issue by BeamWasHere** [huanghongxun/HMCL-PE#205]
**Describe the bug**
Any version (including Quilt, Forge, Fabric, etc.) that is above 1.19.2 (e. g. 1.19.3) crashes on startup. 

**To Reproduce**
1. Launch any version above 1.19.2 (1.19.3 or higher) 
2. See error

**Paste logs here**

<details>
<summary>log file name</summary>

```
Completely ignored arguments: []
[08:25:17] [main/WARN]: Failed retrieving info for group processor
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
	at com.sun.jna.NativeLong.<clinit>(NativeLong.java:35) ~[jna-5.12.1.jar:5.12.1 (b0)]
	at oshi.util.FileUtil.readNativeLongFromBuffer(FileUtil.java:240) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.driver.linux.proc.Auxv.queryAuxv(Auxv.java:59) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.software.os.linux.LinuxOperatingSystem.<clinit>(LinuxOperatingSystem.java:106) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.initProcessorCounts(LinuxCentralProcessor.java:171) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractCentralProcessor.<init>(AbstractCentralProcessor.java:83) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxCentralProcessor.<init>(LinuxCentralProcessor.java:71) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createProcessor(LinuxHardwareAbstractionLayer.java:62) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getProcessor(AbstractHardwareAbstractionLayer.java:68) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.c(SourceFile:75) ~[1.19.3.jar:?]
	at z.a(SourceFile:82) ~[1.19.3.jar:?]
	at z.a(SourceFile:75) ~[1.19.3.jar:?]
	at z.c(SourceFile:52) ~[1.19.3.jar:?]
	at z.a(SourceFile:82) ~[1.19.3.jar:?]
	at z.<init>(SourceFile:52) ~[1.19.3.jar:?]
	at n.<init>(SourceFile:34) ~[1.19.3.jar:?]
	at n.h(SourceFile:274) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
[08:25:17] [main/WARN]: Failed retrieving info for group memory
java.lang.NoClassDefFoundError: Could not initialize class oshi.software.os.linux.LinuxOperatingSystem
	at oshi.hardware.platform.linux.LinuxGlobalMemory.<clinit>(LinuxGlobalMemory.java:47) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.platform.linux.LinuxHardwareAbstractionLayer.createMemory(LinuxHardwareAbstractionLayer.java:57) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.util.Memoizer$1.get(Memoizer.java:87) ~[oshi-core-6.2.2.jar:6.2.2]
	at oshi.hardware.common.AbstractHardwareAbstractionLayer.getMemory(AbstractHardwareAbstractionLayer.java:80) ~[oshi-core-6.2.2.jar:6.2.2]
	at z.a(SourceFile:77) ~[1.19.3.jar:?]
	at z.a(SourceFile:82) ~[1.19.3.jar:?]
	at z.a(SourceFile:77) ~[1.19.3.jar:?]
	at z.c(SourceFile:52) ~[1.19.3.jar:?]
	at z.a(SourceFile:82) ~[1.19.3.jar:?]
	at z.<init>(SourceFile:52) ~[1.19.3.jar:?]
	at n.<init>(SourceFile:34) ~[1.19.3.jar:?]
	at n.h(SourceFile:274) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.a(SourceFile:159) ~[1.19.3.jar:?]
	at net.minecraft.client.main.Main.main(SourceFile:51) ~[1.19.3.jar:?]
[08:25:21] [main/INFO]: Building optimized datafixer
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: Version: 3.2.2 SNAPSHOT
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	 OS: Linux v4.19.81+
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	JRE: 17-internal aarch64
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	JVM: OpenJDK 64-Bit Server VM v17-internal+0-adhoc.runner.openjdk by Oracle Corporation
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: Loading library (system): lwjgl
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	Loaded from java.library.path: /data/user/0/com.tungsten.hmclpe/app_runtime/boat/lwjgl-3/liblwjgl.so
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: Loading library: jemalloc
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	libjemalloc.so not found in java.library.path=/data/user/0/com.tungsten.hmclpe/app_runtime/java/JRE17/lib:/data/user/0/com.tungsten.hmclpe/app_runtime/boat:/data/user/0/com.tungsten.hmclpe/app_runtime/boat/lwjgl-3:/data/user/0/com.tungsten.hmclpe/app_runtime/boat/renderer/virgl
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: 	libjemalloc.so not found in system paths
[08:25:27] [Render thread/INFO]: [STDERR]: [LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: Warning: Failed to instantiate memory allocator: org.lwjgl.system.jemalloc.JEmallocAllocator. Using the system default.
[LWJGL] [08:25:27] [Render thread/INFO]: [STDERR]: MemoryUtil allocator: StdlibAllocator
[08:25:28] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:25:30] [Render thread/INFO]: Setting user: OriginalBeam
[LWJGL] [08:25:30] [Render thread/INFO]: [STDERR]: Loading library: glfw
[LWJGL] [08:25:30] [Render thread/INFO]: [STDERR]: 	Loaded from java.library.path: /data/user/0/com.tungsten.hmclpe/app_runtime/boat/libglfw.so
[08:25:30] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
*** MESA_GLSL_CACHE_DIR is deprecated; use MESA_SHADER_CACHE_DIR instead ***
libEGL warning: No DRI config supports native format 0x5
```
</details>

<details>
<summary>another log file name</summary>

```
<---------paste log here, and delete this line
```
</details>

**Expected behavior**
I expected it to properly launch 1.20.1 (or any other version above 1.19.2)
**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei MatePad Pro 10.8 
 - OS: HarmonyOS 2.0.0 (Build number 2.0.0.264(C10E5R3P2)) 
 - Version: Latest Release

**Additional context**
I do not know how to update lwjgl, so if anyone can, please provide a more in-depth guide on how to update it.

**Comment by Omega596** [comment]
So you know what caused the error? Is it lwjgl?

**Comment by Username10926663** [comment]
**LWJGL**  is outdated just like this launcher. switch to PojavLauncher and enjoy last LWJGL features.
